name: Validate sca integration

on:
  push:
    branches: [ main, devel ]
  pull_request:
    branches: [ main ]

jobs:
  validate-sca:
    name: Validate SCA Policies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Validate SCA YAML syntax
        run: python tests/validate_sca.py sca/pbs4_hardening_independent
  # validate-rules:
  #   name: Validate Detection Rules XML
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Validate XML syntax
  #       run: |
  #         for f in rules/*.xml; do
  #           echo "Checking $f..."
  #           xmllint --noout "$f" && echo "  OK"
  #         done

  check-duplicate-ids:
    name: Check for duplicate rule/check IDs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Check for validate sca
        run: python tests/validate_sca.py sca/pbs4_hardening_independent